### ISSUE TITLE
node-gyp errors build fail

### ISSUE THREAD

**Issue by hellofantastic** [amiya-pattnaik/node-any-jdbc#2]
Hey folks, 

So excited to make use of this package.
Hit snag installing. Output had a lot of V8_deprecated stuff, java file compile errors? console.log output message "Too many errors to list" 

I am on Mojave 10.14.6
Step 1
Noticed trying to start Xode it had missing stuff that wouldn't even install so downloaded Xcode 11.3.1 which is last stable for Mojave.  (Will get back on that, unzipping as I tye this)

Step 2
I am going to try Adding a node version manager , I am on v12.14.1 , need for other things 
But will try older versions of node to see if that gets a build working. 
BUT also issue might be that node-any-jdbc or any-db etc dependencies maybe be outdated.

Any extra insight appreciated as I navigate this

UPDATE: I installed Xcode 11.3.1 and its command line tools, no dice.

```
fatal error: too many errors emitted, stopping now [-ferror-limit=]
19 warnings and 20 errors generated.
make: *** [Release/obj.target/nodejavabridge_bindings/src/java.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Dallas/Sites/node-red-node-jdbc/node_modules/java
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN node-red-contrib-node-jdbc@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! java@0.7.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the java@0.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

Tried node v10.22.1
node-gyp v7.1.0
java
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.265-b01, mixed mode)

Xcode 11.3.1

**Comment by daffigusti** [comment]
I have the same error to
